# Generated by Django 5.1.5 on 2025-01-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancepayment',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='type',
            field=models.CharField(choices=[('taken', 'Taken'), ('paid', 'Paid')], default='taken', max_length=10),
            preserve_default=False,
        ),
    ]
